Mm2PL/dankerino

CHANGELOG.md, badges.json, chatterino.pro, src/Application.cpp, src/Application.hpp, src/providers/dankerino/DankerinoBadges.cpp, src/providers/dankerino/DankerinoBadges.hpp, src/providers/twitch/TwitchMessageBuilder.cpp, src/providers/twitch/TwitchMessageBuilder.hpp
=>  Add Dankerino badges.

src/messages/MessageElement.hpp, src/providers/dankerino/DankerinoBadges.cpp, src/providers/twitch/TwitchMessageBuilder.cpp
- ~~[ ] `CHANGELOG.md` was updated, if applicable~~
=> Add readme entry for dankerino

CHANGELOG.md, src/common/NetworkCommon.hpp, src/common/NetworkPrivate.cpp, src/controllers/commands/CommandController.cpp, src/providers/dankerino/DankerinoBadges.cpp, src/providers/twitch/api/Helix.cpp, src/providers/twitch/api/Helix.hpp
Adds `/settitle` command, `Helix::updateChannel` and PATCH request support.
Partially fix #7
=> Add /settitle command

CHANGELOG.md, src/controllers/commands/CommandController.cpp
=> Add command to set the current stream game

src/singletons/WindowManager.cpp
~~- [ ] `CHANGELOG.md` was updated, if applicable~~
=> Make Dankerino badges controlled using the Chatterino badges setting

CHANGELOG.md, chatterino.pro, src/providers/twitch/api/Helix.cpp, src/providers/twitch/api/Helix.hpp, src/widgets/dialogs/StreamSettingsDialog.cpp, src/widgets/dialogs/StreamSettingsDialog.hpp, src/widgets/dialogs/StreamSettingsDialog.ui, src/widgets/helper/CommonTexts.hpp, src/widgets/splits/Split.cpp, src/widgets/splits/Split.hpp, src/widgets/splits/SplitHeader.cpp
Tags support will be added soon :-)
=> Add GUI for stream settings

CHANGELOG.md, src/providers/twitch/api/Helix.cpp, src/providers/twitch/api/Helix.hpp, src/widgets/dialogs/StreamSettingsDialog.cpp, src/widgets/dialogs/StreamSettingsDialog.hpp, src/widgets/dialogs/StreamSettingsDialog.ui
Adds the ability to edit stream tags in the user interface.
Closes #7
=> Edit stream tags in GUI.

CHANGELOG.md, src/widgets/dialogs/UserInfoPopup.cpp
Adds Supibot AFK integration into User cards. Currently on-demand using a button to not spam Supinic's API as much. Closes #13
=> Add Supibot AFK support

src/widgets/dialogs/UserInfoPopup.cpp, src/widgets/dialogs/UserInfoPopup.hpp
attempt to fix crash
closes #20
=> Move rate limiter to be stored in UserInfoPopup

src/controllers/hotkeys/Hotkey.cpp, src/controllers/hotkeys/Hotkey.hpp
=> add some suggested comments

CHANGELOG.md, src/singletons/Settings.hpp, src/widgets/settingspages/GeneralPage.cpp, src/widgets/splits/Split.cpp
Added a setting so you can toggle the 'Send message as xxxx' placeholder in the chatbox.
=> Toggle textbox placeholder

src/CMakeLists.txt
=> Fix CMake build

CHANGELOG.md, README.md, src/providers/twitch/TwitchMessageBuilder.cpp, src/singletons/Settings.hpp, src/widgets/settingspages/GeneralPage.cpp
=>  Optionally remove spaces between emotes

CHANGELOG.md, src/messages/SharedMessageBuilder.cpp, src/messages/SharedMessageBuilder.hpp, src/providers/irc/IrcMessageBuilder.cpp, src/singletons/Settings.hpp, src/widgets/settingspages/GeneralPage.cpp
=> Split colorizing usernames on IRC and Twitch into two settings

CHANGELOG.md, src/common/CompletionModel.cpp, src/singletons/Settings.hpp, src/widgets/settingspages/GeneralPage.cpp
=> Add setting to lowercase usernames

CHANGELOG.md, src/providers/irc/AbstractIrcServer.cpp, src/providers/twitch/IrcMessageHandler.cpp, src/providers/twitch/TwitchHelpers.cpp, src/providers/twitch/TwitchIrcServer.cpp
=> TMI in 0.5 A presses.

src/messages/layouts/MessageLayoutContainer.cpp, src/providers/twitch/TwitchMessageBuilder.cpp
=> Remove spaces between emotes just visually

CHANGELOG.md, CMakeLists.txt, resources/com.chatterino.chatterino.appdata.xml, src/Application.cpp, src/controllers/commands/CommandController.cpp, src/messages/MessageBuilder.cpp, src/messages/MessageBuilder.hpp, src/messages/MessageElement.hpp, src/messages/layouts/MessageLayoutContainer.cpp, src/messages/layouts/MessageLayoutElement.cpp, src/messages/layouts/MessageLayoutElement.hpp, src/providers/bttv/BttvEmotes.cpp, src/providers/twitch/IrcMessageHandler.cpp, src/providers/twitch/TwitchBadge.cpp, src/singletons/Settings.cpp, src/singletons/Settings.hpp, src/singletons/WindowManager.cpp, src/widgets/Scrollbar.cpp, src/widgets/Scrollbar.hpp, src/widgets/dialogs/EmotePopup.cpp, src/widgets/helper/ChannelView.cpp, src/widgets/helper/NotebookTab.cpp, src/widgets/settingspages/GeneralPage.cpp, src/widgets/settingspages/IgnoresPage.cpp
=> Pull in changes from upstream

src/messages/layouts/MessageLayoutContainer.cpp
=> Fix overlapping emotes

src/widgets/settingspages/GeneralPage.cpp
=> Remove duplicate checkbox

CHANGELOG.md, src/providers/twitch/TwitchMessageBuilder.cpp, src/singletons/Settings.hpp, src/widgets/settingspages/DankerinoPage.cpp
=> IRC Tag fuckery

src/widgets/settingspages/AboutPage.cpp
=> Add a button for the advanced settings

CHANGELOG.md, src/controllers/filters/parser/FilterParser.cpp, src/controllers/filters/parser/Tokenizer.hpp, src/messages/Message.hpp, src/messages/layouts/MessageLayout.cpp, src/providers/twitch/TwitchMessageBuilder.cpp, src/widgets/settingspages/DankerinoPage.cpp
=> Replace orange asterisk with a highlight

src/widgets/settingspages/DankerinoPage.cpp, src/widgets/settingspages/GeneralPage.cpp
=> Clean up settings

src/providers/irc/AbstractIrcServer.cpp
=> clang-format

src/providers/twitch/TwitchMessageBuilder.cpp, src/singletons/Settings.cpp, src/singletons/Settings.hpp, src/widgets/settingspages/DankerinoPage.cpp
=> Disable tag matching when not needed.

src/messages/SharedMessageBuilder.cpp, src/messages/SharedMessageBuilder.hpp, src/providers/irc/IrcMessageBuilder.cpp
=> Simplify IRC Nick colorization

CHANGELOG.md, src/widgets/splits/Split.cpp
Fix for issue [#117](https://github.com/Mm2PL/dankerino/issues/117)
=> surely this will fix it

benchmarks/src/Highlights.cpp, src/Application.hpp, src/messages/SharedMessageBuilder.cpp, tests/src/HighlightController.cpp
Fixed tests for HighlightController by adding override mock functions for `Helix` class members that only exist in dankerino.
This also pulls GH-3808 from upstream
=> Fixed HighlightController tests

CHANGELOG.md, src/widgets/settingspages/AboutPage.cpp
=> Added a warning to not send bug reports to upstream

CHANGELOG.md, src/providers/twitch/TwitchMessageBuilder.cpp, src/singletons/Settings.hpp, src/widgets/settingspages/DankerinoPage.cpp
=> Add support for supabridge
